[tool.poetry]
name = "brettspill"
version = "0.1.0"
description = "Brettpill p√• norsk"
authors = ["Espen Holtebu <espen.holtebu@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
